# Generated by Django 6.0.2 on 2026-03-10 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_crm', '0004_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_tache', models.CharField(choices=[('APPEL', 'Appel téléphonique'), ('RDV', 'Rendez-vous'), ('EMAIL', 'Email à envoyer'), ('RAPPEL', 'Rappel général')], default='RAPPEL', max_length=20)),
                ('date_echeance', models.DateTimeField()),
                ('est_terminee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches_assignees', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='core_crm.contact')),
            ],
        ),
    ]
