# Generated by Django 6.0.2 on 2026-03-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_crm', '0005_tache'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampagneRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Ex: Newsletter Mensuelle', max_length=255)),
                ('sujet', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('frequence', models.CharField(choices=[('HEBDO', 'Chaque Semaine'), ('MENSUEL', 'Chaque Mois')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
